backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: elijahbocz
    api_key: 242768671424363
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Bio Page"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: "CV Page"
        name: "cv"
        file: "content/cv.md"
        fields:
          - {label: Body, name: body, widget: markdown}
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.md"
        fields:
          - {label: Body, name: body, widget: markdown}