backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: elijahbocz
    api_key: 242768671424363
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
      - label: "Bio Page"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, widget: markdown }
      - label: "CV Page"
        name: "cv"
        file: "content/cv.md"
        fields:
          - {label: Education, name: education, widget: markdown}
          - {label: Exhibitions, name: exhibitions, widget: markdown}
          - {label: Press, name: press, widget: markdown}
          - {label: Selected Collections, name: selectedCollections, widget: markdown}
          - {label: Honors/Awards, name: honorsAwards, widget: markdown}